### DISCUSSION TITLE
Support the "actions" helper method inside the Arbre "table_for" component

### DISCUSSION THREAD

**Discussion by ilunglee** [CMDBrew/adminterface#106] [Feature Request & Ideas]
# Problem
The `index` page for ActiveAdmin has the `actions` method that helps render resource actions.

```ruby
index do
  id_column
  ...
  actions
end
```

However, the `table_for` component doesn't support this method, so we have to build out the actions ourselves. 
It becomes repetitive when we want to have consistent styles for the `table_for` buttons.

```ruby
table_for resource.products do
  column("", class: "text-right") do |product|
    link_to t("active_admin.view"), [:admin, product], class: "btn btn-light btn-sm"
  end
end
```

# Proposed solution
## Helper method
Add the `actions` method for `table_for`. It should behave exactly like the `actions` on the `index` page, which supports both `inline` and `dropdown` styles.
```ruby
table_for resource.products do
  actions do
    item t("active_admin.view"), [:admin, product]
  end
end
```

## Customization
Add the css class options in `css_classes.yml` from:
```yaml
table_for: table
```

to:
```yaml
table_for: 
  table: table
  actions:
    dropdown:
      toggle: btn btn-sm btn-light
    buttons:
      group: btn-group
      item: btn btn-sm btn-light
```

### Automatically generate routes 
Similar to the `index` page, the `actions` method will automatically generate the routes based on the configurations of the resource inside ActiveAdmin
```ruby
table_for resource.products do
  actions
end
```
